/*
 * ICSMDisplay.java
 *
 * Created on March 19, 2010, 10:37 AM
 */

package falcon;

/**
 *
 * @author  WA0003EN
 */
public class ICSMDisplay extends java.awt.Frame {
    
    protected FusionART ICSM;
    
    protected String allWeapons [] = new String [] {"FLAK_CANNON", "MINIGUN",
            "ROCKET_LAUNCHER", "LINK_GUN", "BIO_RIFLE", "LIGHTNING_GUN",
            "SHOCK_RIFLE", "SNIPER_RIFLE", "ASSAULT_RIFLE", "SHIELD_GUN"};
    protected String allItem [] =new String[]{"Medical Kit (Small)", "Medical Kit (Large)", 
            allWeapons[0], allWeapons[1], allWeapons[2], allWeapons[3], allWeapons[4], 
            allWeapons[5], allWeapons[6], allWeapons[7], allWeapons[8], allWeapons[9], };

    /** Creates new form ICSMDisplay */
    public ICSMDisplay() {
        initComponents();
        setVisible(true);
    }
    
    public void setICSM(FusionART cism){
        ICSM=cism;
        
        for(int i=0;i<cism.numCode;i++){
            this.jComboBox1.addItem(new String(""+i));
        }    
        
        this.jComboBox2.addItem(new String("Medical Kit (Small)"));
        this.jComboBox2.addItem(new String("Medical Kit (Large)"));
        for(int i=0;i<allWeapons.length;i++){
            this.jComboBox2.addItem(new String(""+allWeapons[i]));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EVENTS ONLINE DISPlAY");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View A Code");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bodoni MT", 0, 18));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Results");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 153));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Retrieve An Item");

        jComboBox1.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a code index to view" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a item to retrieve" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)))
                                .addGap(205, 205, 205))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
     if (this.jComboBox1.getSelectedIndex() == 0) {
        return;
    }

    int ptr = this.jComboBox1.getSelectedIndex() - 1;
    this.jTextArea1.setText(getCodeDispt(ptr));
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox2actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2actionPerformed
// TODO add your handling code here:
    if (this.jComboBox2.getSelectedIndex() == 0) {
        return;
    }

    int ptr = this.jComboBox2.getSelectedIndex() - 1;
    String str = "The map areas containing "+this.allItem[ptr]+" are:\n";
    
    double[][] inPattern=new double[this.ICSM.numSpace][];
    for (int k=0;k<ICSM.numSpace;k++) {
         inPattern[k] = new double [ICSM.len[k]];
    }
                
    System.arraycopy(resetStatus(inPattern[1]), 0, inPattern[1], 0, inPattern[1].length);
    inPattern[1][ptr*2]=1;
    inPattern[1][ptr*2+1]=0;
    
    int[] winners = this.ICSM.findWinnerK(inPattern, ICSM.FUZZYART, 0,0.18);
    System.out.print("one retrieve cue: ");
    for(int l=0;l<inPattern[1].length;l++){
        System.out.print(inPattern[1][l]+" ");
    }
    System.out.println("");
    
    if(winners==null){
        System.out.println("Unsuccessful retrieve!!!!");
        this.jTextArea1.setText(str+"N.A.");
        return;
    }
    
    for(int i=0;i<winners.length;i++){
        str+="Area ";    
        double[] codeArr=this.ICSM.weight[winners[i]][0];
       // int locIndex=-1;
    
     //System.out.print("one winner cue parts ");
    //for(int l=0;l<ICSM.weight[winners[i]][1].length;l++){
      //  System.out.print(ICSM.weight[winners[i]][1][l]+" ");
   // }
    //System.out.println("");
    
      /*  for(int j=0;j<codeArr.length/2;j++){
            if(codeArr[2*j]==1){
                locIndex=j;
                break;
            }
        }
    
        int[] locArea=getMapArea(locIndex);
        str+=Event.xGridIndex[locArea[0]]+"_";
        str+=locArea[2];
        str+=("_"+Event.yGridIndex[locArea[1]])+"\n";*/
        
        EventPattern e=new EventPattern();
        e.x=codeArr[0];
        e.x_compl=codeArr[1];
        e.z=codeArr[2];
        e.z_compl=codeArr[3];
        e.y=codeArr[4];
        e.y_compl=codeArr[5];
        str+=e.getMapArea()+"\n";
    }
    
    this.jTextArea1.setText(str);
}//GEN-LAST:event_jComboBox2actionPerformed

 private double[] resetStatus(double[] arr){
        for(int j=0;j<arr.length;j++){
            if(j%2==0){
                arr[j]=0;
            }
            else{
                arr[j]=1;
            }
        }
        
        return arr;
    }

private String getCodeDispt(int codeIndex){
    String str="Map Area ";    
    double[][] codeArr=this.ICSM.weight[codeIndex];
    
    EventPattern e=new EventPattern();
    e.x=codeArr[0][0];
    e.x_compl=codeArr[0][1];
    e.z=codeArr[0][2];
    e.z_compl=codeArr[0][3];
    e.y=codeArr[0][4];
    e.y_compl=codeArr[0][5];
    str+=e.getMapArea();
    
    for(int i=0;i<codeArr[1].length/2;i++){
        if(codeArr[1][2*i]==1){
            str+=this.allItem[i]+"; ";
        }
    }
    
    return str+"\n";
}

private int[] getMapArea(int locIndex){
    int[] xyz=new int[3];
    
    xyz[0]=locIndex/(Event.divZ*Event.divY);
    locIndex=locIndex-xyz[0]*(Event.divZ*Event.divY);
    xyz[1]=locIndex/Event.divZ;
    xyz[2]=locIndex%Event.divZ;
    
    System.out.println("Retrieved locIndex: x="+xyz[0]+", y="+xyz[1]+" ,z="+xyz[2]);
    
    return xyz;
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ICSMDisplay().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
